package Visual;

import Data.Productos;

import javax.swing.*;
import java.awt.*;

public class CheckOut {


    private static int[] cart = {0, 0, 0, 0, 0, 0, 0, 0};
    private JLabel saldoLabel;
    private JLabel SALDO;
    private JButton pagarButton;
    private JButton cerrarButton;
    private JLabel CartList;
    private JPanel mainPanel;
    private JFrame principal;

    public CheckOut() {
        principal = new JFrame("checkOut");

        principal.add($$$getRootComponent$$$());

        principal.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        calculateSaldo();
        setCartListLabel();

        principal.setVisible(true);
    }


    public static void addToCart(int id) {
        byte j = 0;
        for (int i : cart
        ) {
            if (i == 0) {
                cart[j] = id;
            } else {
                j += 1;
            }
        }
    }

    public static void removeFromCart(int id) {
        byte j = 0;
        for (int i : cart
        ) {
            if (i == id) {
                cart[j] = 0;
            } else {
                j += 1;
            }
        }
    }

    private void calculateSaldo() {
        int saldo = 0;
        byte j = 0;
        Productos[] productos = Productos.getInventario();
        for (int i : cart
        ) {
            if (i != 0) {
                saldo += productos[j].getValor();
            } else {
                j += 1;
            }
        }
        SALDO.setText(String.valueOf(saldo));
    }

    private void setCartListLabel() {
        String cartList = "";

        byte j = 0;
        Productos[] productos = Productos.getInventario();
        for (int i : cart
        ) {
            if (i != 0) {
                cartList += "\nProducto" + productos[j].getId();
            } else {
                j += 1;
            }
        }
        CartList.setText(cartList);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        saldoLabel = new JLabel();
        saldoLabel.setText("Saldo");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(saldoLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer2, gbc);
        SALDO = new JLabel();
        SALDO.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(SALDO, gbc);
        pagarButton = new JButton();
        pagarButton.setText("pagar");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(pagarButton, gbc);
        cerrarButton = new JButton();
        cerrarButton.setText("cerrar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(cerrarButton, gbc);
        CartList = new JLabel();
        CartList.setText("Cart List");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(CartList, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
