package Visual;

import Logic.CheckCredentials;
import Logic.GetDataFromUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;


public class Login implements CheckCredentials {
    private JPanel panel1;
    private JButton logInButton;
    private JTextField usernameInput;
    private JPasswordField passwordInput;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JLabel errorMessage;
    private JFrame frame;


    public Login() {
        frame = new JFrame("login");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add($$$getRootComponent$$$());
        frame.setVisible(true);
        logInButton.addMouseListener(new MouseAdapter() {
            /**
             * {@inheritDoc}
             *
             * @param e
             */

            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getSource() == logInButton) {
                    GetDataFromUI.setUsername(usernameInput.getText());
                    GetDataFromUI.setPassword(String.valueOf(passwordInput.getPassword()));
                    if (canLogin(isUserUnal(GetDataFromUI.getUsername()), isPasswordCorrect(GetDataFromUI.getPassword()))) {
                        loginSucced();
                    } else {
                        loginFailed();
                    }

                }

            }

        });

    }

    @Override
    public boolean isUserUnal(String username) {

        char[] patron = "lpilonieta".toCharArray();
        byte i = 0;
        for (char character : username.toCharArray()
        ) {
            if (patron[i] == character) {
                i += 1;
            } else {
                return false;
            }
        }
        return true;
    }

    @Override
    public boolean isPasswordCorrect(String password) {
        char[] patron = "1234".toCharArray();
        byte i = 0;
        for (char character : password.toCharArray()
        ) {
            if (patron[i] == character) {
                i += 1;
            } else {
                return false;
            }
        }
        return true;
    }

    @Override
    public void loginSucced() {

        frame.setVisible(false);
        Home homeFrame = new Home();
        System.out.println("yupi, login");
        errorMessage.setText("");

    }


    @Override
    public void loginFailed() {
        usernameInput.setText("");
        passwordInput.setText("");
        errorMessage.setText("Revise sus datos,\n Usuario o contraseña incorrectos");

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(passwordLabel, gbc);
        logInButton = new JButton();
        logInButton.setText("LogIn");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(logInButton, gbc);
        usernameLabel = new JLabel();
        usernameLabel.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(usernameLabel, gbc);
        usernameInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(usernameInput, gbc);
        passwordInput = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(passwordInput, gbc);
        errorMessage = new JLabel();
        errorMessage.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(errorMessage, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
