package Visual;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class menu {
    private JPanel menu;
    private JLabel masDetalles;
    private JButton cerrarButton;
    private JFrame frame;

    public menu(String data) {
        frame = new JFrame("Mas Opciones");
        frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        masDetalles.setText(data);
        frame.add($$$getRootComponent$$$());
        frame.setVisible(true);
        cerrarButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                frame.setVisible(false);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        menu = new JPanel();
        menu.setLayout(new FlowLayout(FlowLayout.LEADING, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Mas detalles del producto");
        menu.add(label1);
        masDetalles = new JLabel();
        masDetalles.setText("Label");
        menu.add(masDetalles);
        cerrarButton = new JButton();
        cerrarButton.setText("cerrar");
        menu.add(cerrarButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return menu;
    }

}
